### PR TITLE
Enable Gradle Configuration Caching

### PR DESCRIPTION
**Pull request by liutikas**

### CODE REVIEW

**Comment by asodja** [comment]
Also here, could you just sign-off the commit to make DCO check happy?

**Comment by liutikas** [comment]
Done

**Comment by asodja** [comment]
Thank you!

It seems we have some problems that need to be fixed before we use cc, e.g. ` ./gradlew test --dry-run ` shows:
```
6 problems were found storing the configuration cache.
- Task `:generateHtmlReportJavaScript` of type `com.moowork.gradle.node.npm.NpxTask`: cannot serialize object of type 'com.moowork.gradle.node.npm.NpmInstallTask', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:generateHtmlReportJavaScript` of type `com.moowork.gradle.node.npm.NpxTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:installAndroidSdk` of type `tasks.InstallAndroidSdkTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:npmInstall` of type `com.moowork.gradle.node.npm.NpmInstallTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:npmSetup` of type `com.moowork.gradle.node.npm.NpmSetupTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

So node plugin needs upgrade and there are also two issues in our scripts with `AndroidStudioSystemProperties` and `installAndroidSdk.onlyIf()`. I will leave this PR open till someone finds time to fix it.

**Comment by asodja** [comment]
Note to future reader: upgrade of node seems easy, onlyIf can be fixed with:
```
val installAndroidSdk = tasks.register<InstallAndroidSdkTask>("installAndroidSdk") {
   ...
    val autoDownloadAndroidSdk = extension.autoDownloadAndroidSdk
    onlyIf { autoDownloadAndroidSdk.get() }
}
```

`AndroidStudioSystemProperties` problem seems it needs some more attention.

**Comment by asodja** [comment]
Thanks for the contribution!

**Pull request merged**
