### PR TITLE
Fix build warnings after Gradle 7.5 update

### PR DESCRIPTION
**Pull request by nevack**
These changes are trivial.

### CODE REVIEW

**Comment by nevack** [comment]
Signed Off all commits

**Comment by asodja** [comment]
Hi @nevack,

thanks for the contribution! It looks good, except that we still have to build for Java8. Due to that could you drop the last commit and force push it again?

JDK11 is required for building a project since `org.jetbrains.intellij` plugin that is used in `studio-plugin` project  is compiled for Java11. But `studio-plugin` is not used directly by the profiler, but it's used by Android Studio when you profile project sync with Android Studio.

**Comment by nevack** [comment]
That's what I expected and this is the reason this change is in the last commit - to drop it if it's not right.
Thanks for clarification.

Maybe it's worth mentioning in README that you need both JDK 8 and JDK 11 to build the project?

**Comment by asodja** [comment]
Thanks! Yeah, if you would like to update that, feel free to do so.

**Comment by asodja** [comment]
Thanks for the contribution!

**Pull request merged**
