### PR TITLE
Run help on root project to speed up project probe

### PR DESCRIPTION
**Pull request by joshfriend**
Related to #484, running `help` takes a significant amount of time in our build because it is so large and it configures the whole project just to find a few basic pieces of info. Using `:help` on the root project makes this considerably faster.

### CODE REVIEW

**Comment by asodja** [comment]
I think that makes sense, there are some tests failing where we check that `help` was run, e.g.:
```
logFile.find("<tasks: [help]>").size() == 2
|       |                       |      |
|       []                      0      false
```

I replacing `<tasks: [help]>` with `<tasks: [:help]>` should fix tests.

**Comment by joshfriend** [comment]
I'm having trouble running the tests locally with an ARM mac, possibly because this supports such old gradle versions. For now i just globally replaced the expected output but I doubt that is going to pass

**Comment by asodja** [comment]
I think it should do a trick. Let's see. And I see StudioPluginIntegrationTest is flaky so ignore that..

We need to upgrade Gradle version, thanks for a reminder.

**Comment by joshfriend** [comment]
Ok, I might have it this time 😆 
Updated the `help` scenarios in the integration tests to run `:help` as well (instead of `help`) and got some of them to pass locally (by updating the `supportedGradleVersions` array somewhat)

**Comment by asodja** [comment]
I am also using arm, but it works for me. Maybe it's an issue for you, since we request toolchains for JDK8 and maybe you don't have arm version of JDK8?

**Comment by asodja** [comment]
I adjusted `ProfilerIntegrationTest` since there was one more failure, this is now good to merge. Thanks for the contribution!

**Comment by joshfriend** [comment]
> maybe you don't have arm version of JDK8?

Yeah that must be why, I checked and I don't have one installed, I'll get one for next time! Foojay resolver would be a nice addition to do that automatically.

Thanks for fixing the remaining issues, hope it wasn't too annoying for you!

**Pull request merged**
