### PR TITLE
Add additional version information for Bazel and Buck

### PR DESCRIPTION
**Pull request by sunyal**

### CODE REVIEW

**Comment by oehme** [comment]
This change doesn't compile. Please see the build output (you can log in as a guest)

**Comment by sunyal** [comment]
@oehme it has been a while, so it conflicts now.  I'll take a look.

**Comment by oehme** [comment]
There are no conflicts. Also, conflicts have no effect on builds of your branch. [This line](https://github.com/gradle/gradle-profiler/pull/68/files#diff-a3b8709a6bb813609d60ae83f2e0f648R11) just can't compile :)

**Comment by sunyal** [comment]
Ok sure I'll take care of it

**Comment by Nohands253** [comment]
Ty

**Comment by sunyal** [comment]
nm I'll look into it - looks to be a `./buckw` path issue

**Pull request closed without merging**
