### PR TITLE
Make chrome-trace tmp file copy work correctly

### PR DESCRIPTION
**Pull request by liutikas**
File#moveTo only works when the two files are within the same file system. Some Linux distributions set /tmp/ to be mounted to a different file system, thus causing moveTo fail with:
Caused by: java.lang.RuntimeException: Failed to move the trace file from a temporary location (/tmp/gradle-trace9055990495551523261.html) to the final location (/ssd/ssd1/temp/gradle-profiler/profile-out-9/5.6.4-trace.html)
	at org.gradle.trace.AsynchronousTraceWriter.finish(AsynchronousTraceWriter.java:40)
	at org.gradle.trace.TraceResult.finalizeTraceFile(TraceResult.java:48)
	at org.gradle.trace.GradleTracingPlugin$TraceFinalizerAdapter.buildFinished(GradleTracingPlugin.java:57)
...

This change replaces File#moveTo with Apache FileUtils#copyFile that works correctly in such situations.

### CODE REVIEW

**Comment by liutikas** [comment]
This is a follow up to actually fix https://github.com/gradle/gradle-profiler/pull/79

**Comment by liutikas** [comment]
> Instead of working around this, I think we should instead create the temp file right next to the final destination and then rename it once done. This is guaranteed to work, as both will be on the same filesystem.

Should we just write to the `traceFile` file directly? As far as I can tell the only reason we have a temp file is to prevent a write if generating a trace fails which sounds like a bug in the first place.

**Comment by oehme** [comment]
That's a fair point, it's not like we're writing to some sensitive or contested location 👍

**Comment by liutikas** [comment]
Moved to writing directly to the final destination.

I had to add if (File#exists()) { File#delete() } as we run tracer several times (warm-up).

**Pull request merged**
