### PR TITLE
Chrome traces: normalize file paths in build operation display names

### LINKED ISSUE #293: Chrome trace data with backslash cannot be opened on macOS
I'm assuming that Chrome just won't open those chrome traces on other operating systems as well. The key point here is chrome trace generated on Windows most likely will contain backslash because of the file path separator. This causes an error when opening in the lines of "Unexpected token...".

I was able to "fix" the chrome trace by doubling all backslash in the embedded JSON data. It would be much better if the profiler could generate valid JSON data without needing manual editing.

### PR DESCRIPTION
**Pull request by jjohannes**
Fixes #293

### CODE REVIEW

**Comment by asodja** [comment]
I wonder if we could add some tests, so we don't break it in future. 🤔

**Comment by jjohannes** [comment]
I did initially not add a test, because there were no tests at all in the project and I didn't know where to put it.

I now added a commit that configures the subprojects to have Spock tests (feel free to adjust or move the test somewhere else).

I added a test that checks if the normalization works for all `Gradle*BuildOperationListenerInvocationHandler`s that accept `BuildOperationDescriptor`s as they are now. Hope that's sufficient for this.

**Comment by asodja** [comment]
Awesome, thanks!

**Comment by asodja** [comment]
Thanks for your contribution!

**Pull request merged**
