### PR TITLE
Add git-commit to Profiler Scenarios

### PR DESCRIPTION
**Pull request by AndrewReitz**
Adds ability to checkout a previous commit, run the profiler
against that commit, and then reverts back to the original checked
out branch.

Signed-off-by: Andrew Reitz <aj.reitz@gmail.com>

### CODE REVIEW

**Comment by oehme** [comment]
How is this different from git-checkout?

**Comment by AndrewReitz** [comment]
I thought that git-checkout was supposed to simulate large changes between the current branch and a previous commit, where as this is supposed to profile a specific commit.

**Comment by AndrewReitz** [comment]
Ok, I'll update to so that. Would you be open to a mutator that checks out different branches as well?

**Comment by oehme** [comment]
I don't think there should be a difference. You checkout a reference, which can be any commit or branch or tag.

**Comment by AndrewReitz** [comment]
@oehme When you say to change the second commit is optional, do you mean just allow cleanup to be null, since it looks like that is currently possible without any modifications to the code, or is there something else that would need to be done?

**Comment by oehme** [comment]
If it already works, all the better :) I didn't check.

**Comment by AndrewReitz** [comment]
I created tests to verify. Would you be interested in me submitting a pr?

**Comment by oehme** [comment]
Of course 👍

**Pull request closed without merging**
